# This is a basic workflow to help you get started with Actions

name: Docs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Install deps
        run: sudo apt-get install python3-sphinx


      # Runs a single command using the runners shell
      - name: autodoc
        run: |
          cd docs
          sphinx-apidoc -f -o docs ..

      # Runs a set of commands using the runners shell
      - name: Make the docs
        run: make html
      - name: git pull
        run: |
          git config pull.ff only
          git pull --all
      - name: Commit
        run: |
          git config --global user.name 'Doc Updater[bot]'
          git config --global user.email 'ThatXliner@users.noreply.github.com'
          git commit -am ":robot: | :memo: -> Updated docs! [skip ci]" >  /dev/null || echo "Already up to date ğŸ‘"
          git pull --all
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
